### ISSUE TITLE
Change the script name?

### ISSUE THREAD

**Issue by petsam** [petsam/safesync#1]
I was thinking of another name that points to the _One Mirror_ maintenance strategy.

Maybe rename to `onemirror` ?

Any ideas?

**Comment by sgse** [comment]
# MOMS
M-anjaro
O-ne
M-irror
S-cript  or S-afesync
or only MOM ;)

Didn't check if it already exists in this context.
Some icon needed? ;)
cu :-)

**Comment by sgse** [comment]
Ἑλλάς Petsam , right?, did not find the Original in WWW ;-)

**Comment by petsam** [comment]
> or only MOM
I find it proper fit!! Some of us always need their mom to protect them from accidents!!
From a quick search on github, the name is free. We should wait for any other proposals, else it's either mom or moms.

**Comment by petsam** [comment]
> Ἑλλάς Petsam , right?

Actually it's from my webpage name. It is all letters compounded.
ΘΕΩΡΕΙΟ

**Comment by sgse** [comment]
ΘΕΩΡΕΙΟ
Now that you say it, I see it too. ;-)

**Comment by sgse** [comment]
Just MOMS ;-)

![moms-r](https://user-images.githubusercontent.com/17575778/55123781-2ab90b80-5104-11e9-8dbf-d72ffe527b08.png) 
![moms-e](https://user-images.githubusercontent.com/17575778/55123787-30aeec80-5104-11e9-96e2-7762cb108d88.png)

**Comment by petsam** [comment]
Name change implemented!
## M1mS - Manjaro 1(One) Mirror Sync(ing)
